### PR TITLE
chore: moved src to root

### PR DESCRIPTION
**Pull request by JP-sDEV**
Refactored to move the `src` folder into the root of the project. `kanonproxy/kanonproxy/build.gradle.kts` was combined with `kanonproxy/build.gradle.kts` (i.e. the root gradle build).

The combined gradle build was tested on Eclipse 4.32.0 and had no issues. 

Cheers! :)

### CODE REVIEW

**Comment by compscidr** [comment]
Looks good - I think probably something merged between when you started and now, so if you merge in `origin/main` and then move the other files over as well it should be good.

Also if you could remove the  `.project` and `.settings` files (and optionally add entries to `.gitignore` so they don't get included again) that would be great.

**Comment by JP-sDEV** [comment]
Sounds good, I'll get those changes in the pull request ASAP! Thanks! :)

**Comment by JP-sDEV** [comment]
Pushed the changes according to the feedback! Cheers! :)

**Comment by compscidr** [comment]
I think something went wrong with the merge - there are now two copies of Session and KAnonProxy. If you could remove the one's in the `bin` folder, I think we're ready to merge.

**Comment by JP-sDEV** [comment]
Done! The duplicate files where removed. :)

**Pull request merged**
